app:
  name: web-proxy-api
  port: 3000
admin:
  username: admin
  password: $encrypted$fb51cc39226e7f085dc19b2bc2006ccd$fa7e0f721f0feb2e614bce2de008771e2e76758b1b079835ddcdc00bc95fac98c08aa03756958c872cff8dd3286d990fe0409e9c1b525945a8dcd5a3d0cf2e57
keys:
  - your-api-key-here
  - another-key-here
projects:
  deepseek:
    enabled: true
  grok:
    enabled: true
grok:
  base_url: ""
  x_statsig_id: ""
  dynamic_statsig: false
  temporary: false
  proxy_url: ""
  proxy_pool_url: ""
  proxy_pool_interval: 300
  retry_status_codes:
    - 401
    - 429
  filtered_tags: xaiartifact,xai:tool_usage_card,grok:render
  show_thinking: true
  image_mode: url
  image_cache_max_size_mb: 500
  video_cache_max_size_mb: 500
logging:
  level: info
  format: json
