app:
  name: web-proxy-api
  port: 3000
admin:
  username: admin
  password: $encrypted$f993c2038c869c312cfd3c1384d36f84$17b18a9e04c5b6c9c29a92cc6e583b7d55ea5bc244b894877bde3e9a5b79fc9ac65178baa4389b86a0859c2662f03906c00b27597d275d2ebd765b78d73df986
keys:
  - your-api-key-here
  - another-key-here
projects:
  deepseek:
    enabled: true
  grok:
    enabled: true

grok:
  base_url: ""
  x_statsig_id: ""
  dynamic_statsig: false
  temporary: false
  proxy_url: ""
  proxy_pool_url: ""
  proxy_pool_interval: 300
  retry_status_codes:
    - 401
    - 429
  filtered_tags: "xaiartifact,xai:tool_usage_card,grok:render"
  show_thinking: true
  image_mode: "url"
  image_cache_max_size_mb: 500
  video_cache_max_size_mb: 500
logging:
  level: info
  format: json
